### ISSUE TITLE
Uncaught TypeError: minimap.setCharWidth is not a function

### ISSUE THREAD

**Issue by noameppel** [mrodalgaard/atom-expose#20]
Upon launching Expose using cmd+shift+e, I get an error:

**Atom Version**: 1.5.3
**System**: Mac OS X 10.11.3
**Thrown From**: [expose](https://github.com/mrodalgaard/atom-expose) package, v0.11.1
### Stack Trace

Uncaught TypeError: minimap.setCharWidth is not a function

```
At /Users/Foo/.atom/packages/expose/lib/expose-tab-view.coffee:73

TypeError: minimap.setCharWidth is not a function
    at /Users/Foo/.atom/packages/expose/lib/expose-tab-view.coffee:73:17
    at Provider.module.exports.Provider.provide (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/service-hub/lib/provider.js:30:52)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/service-hub/lib/service-hub.js:55:26
    at doNTCallback0 (node.js:419:9)
    at process._tickCallback (node.js:348:13)
```
### Commands

```
     -1:25.7.0 core:save (atom-text-editor.editor.is-focused)
     -1:23.7.0 emmet:toggle-comment (atom-text-editor.editor.is-focused)
     -1:23.7.0 editor:toggle-line-comments (atom-text-editor.editor.is-focused)
     -1:23.6.0 core:save (atom-text-editor.editor.is-focused)
     -1:21.6.0 core:backspace (atom-text-editor.editor.is-focused)
  2x -1:21 core:save (atom-text-editor.editor.is-focused)
  3x -1:05.1.0 core:undo (atom-text-editor.editor.is-focused)
     -1:02.7.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:02.5.0 core:save (atom-text-editor.editor.is-focused)
  3x -0:59 core:close (atom-text-editor.editor.is-focused)
     -0:51.9.0 find-and-replace:show (atom-text-editor.editor.is-focused)
     -0:49.7.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:31.9.0 expose:toggle (atom-text-editor.editor.is-focused)
     -0:26.1.0 core:close (atom-text-editor.editor.is-focused)
     -0:17.8.0 editor:select-to-end-of-line (atom-text-editor.editor.is-focused)
  2x -0:16.8.0 expose:toggle (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "wrap-guide",
      "activate-power-mode",
      "nitrogen",
      "imdone-atom-github",
      "live-archive"
    ],
    "followSymlinks": false,
    "ignoredNames": [
      ".git",
      ".svn",
      ".DS_Store",
      ".unison",
      ".hg",
      "CVS",
      ".AppleDouble",
      ".LSOverride",
      ".Spotlight-V100",
      ".Trashes",
      "Thumbs.db",
      "desktop.ini",
      "*.lock",
      "*.sock",
      "*.pid",
      "*.sw?",
      ".unison*",
      "._*",
      "*~"
    ],
    "themes": [
      "seti-ui",
      "seti-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
atom-beautify, v0.28.16
clipboard-history, v0.6.6
color-picker, v2.0.13
docblockr, v0.7.3
emmet, v2.3.13
expose, v0.11.1
linter, v1.10.0
linter-php, v1.0.5
minimap, v4.15.0
minimap-split-diff, v0.2.0
pigments, v0.18.0
project-manager, v2.6.5
remote-edit, v1.8.22
seti-syntax, v0.4.1
seti-ui, v0.8.1
wordpress-api, v1.2.1

# Dev
No dev packages
```

**Comment by mrodalgaard** [comment]
Thank you for the report, but I need more details to reproduce.

Does this happen every time you run expose? Have you tried updating your minimap package? Why do you have the `minimap-split-diff` installed, when you do not have the `Split Diff` package installed?
