### ISSUE TITLE
Failed to load the expose package

### ISSUE THREAD

**Issue by pabl0xf** [mrodalgaard/atom-expose#22]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.7.0
**System**: Unknown Windows Version
**Thrown From**: [expose](https://github.com/mrodalgaard/atom-expose) package, v0.11.1
### Stack Trace

Failed to load the expose package

```
At UNKNOWN: unknown error, open 'C:\Users\pablof\.atom\compile-cache\less\40e22529c8729b65e1d700a7ae3f73d57ed1288f\content\8fef58e2678e0ca48afad640ad68af9b9ab53a15\themes.json'

Error: UNKNOWN: unknown error, open 'C:\Users\pablof\.atom\compile-cache\less\40e22529c8729b65e1d700a7ae3f73d57ed1288f\content\8fef58e2678e0ca48afad640ad68af9b9ab53a15\themes.json'
    at Error (native)
    at Object.fs.openSync (fs.js:584:18)
    at Object.module.(anonymous function) [as openSync] (ATOM_SHELL_ASAR.js:159:20)
    at Object.fs.writeFileSync (fs.js:1234:33)
    at Object.fsPlus.writeFileSync (C:\Users\pablof\AppData\Local\atom\app-1.7.0\resources\app.asar\node_modules\fs-plus\lib\fs-plus.js:279:17)
    at LessCache.module.exports.LessCache.writeJson (C:\Users\pablof\AppData\Local\atom\app-1.7.0\resources\app.asar\node_modules\less-cache\lib\less-cache.js:155:17)
    at LessCache.module.exports.LessCache.putCachedCss (C:\Users\pablof\AppData\Local\atom\app-1.7.0\resources\app.asar\node_modules\less-cache\lib\less-cache.js:238:12)
    at LessCache.module.exports.LessCache.cssForFile (C:\Users\pablof\AppData\Local\atom\app-1.7.0\resources\app.asar\node_modules\less-cache\lib\less-cache.js:287:12)
    at LessCompileCache.module.exports.LessCompileCache.cssForFile (C:\Users\pablof\AppData\Local\atom\app-1.7.0\resources\app.asar\src\less-compile-cache.js:40:25)
    at ThemeManager.module.exports.ThemeManager.loadLessStylesheet (C:\Users\pablof\AppData\Local\atom\app-1.7.0\resources\app.asar\src\theme-manager.js:279:33)
    at ThemeManager.module.exports.ThemeManager.loadStylesheet (C:\Users\pablof\AppData\Local\atom\app-1.7.0\resources\app.asar\src\theme-manager.js:257:21)
    at C:\Users\pablof\AppData\Local\atom\app-1.7.0\resources\app.asar\src\package.js:435:54
    at Array.map (native)
    at Package.module.exports.Package.loadStylesheets (C:\Users\pablof\AppData\Local\atom\app-1.7.0\resources\app.asar\src\package.js:433:59)
    at C:\Users\pablof\AppData\Local\atom\app-1.7.0\resources\app.asar\src\package.js:112:19
    at Package.module.exports.Package.measure (C:\Users\pablof\AppData\Local\atom\app-1.7.0\resources\app.asar\src\package.js:92:15)
    at Package.module.exports.Package.load (C:\Users\pablof\AppData\Local\atom\app-1.7.0\resources\app.asar\src\package.js:106:12)
    at PackageManager.module.exports.PackageManager.loadPackage (C:\Users\pablof\AppData\Local\atom\app-1.7.0\resources\app.asar\src\package-manager.js:457:14)
    at C:\Users\pablof\AppData\Local\atom\app-1.7.0\resources\app.asar\src\package-manager.js:402:19
    at Config.module.exports.Config.transact (C:\Users\pablof\AppData\Local\atom\app-1.7.0\resources\app.asar\src\config.js:312:16)
    at PackageManager.module.exports.PackageManager.loadPackages (C:\Users\pablof\AppData\Local\atom\app-1.7.0\resources\app.asar\src\package-manager.js:397:19)
    at C:\Users\pablof\AppData\Local\atom\app-1.7.0\resources\app.asar\src\atom-environment.js:743:28
```
### Commands

```
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "language-java",
      "spell-check"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
auto-encoding, v0.5.3
auto-indent, v0.5.0
autocomplete-php, v0.3.7
less-than-slash, v0.13.0
local-history, v3.2.3
minimap, v4.21.0
node-debugger, v1.4.6
php-cs-fixer, v2.5.6
php-debug, v0.2.2
php-getters-setters, v0.5.5
php-integrator-navigation, v0.5.0
Remote-FTP, v0.7.20
space-tab, v0.4.2

# Dev
No dev packages
```

**Comment by mrodalgaard** [comment]
Hi @pabl0xf, has this happen more than once? It looks like a cache problem with Atom. `themes.json` from the cache location could not be found and there is no `themes.json` in atom-expose.
